spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cloudtodo?options=-c%20TimeZone=UTC
    username: cloudtodo
    password: cloudtodo_dev_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html